import { validPublicPhone, LEASE_MONTHS } from "../../lib/customer-input";
import { ensureDb, getRawDb } from "../../../db";
import { getCatalog } from "../../lib/catalog";
import { calculateInstallment, salePrice, type LeaseProgram } from "../../lib/leasing";
import { getLeasingPublicConfig } from "../../lib/leasing-public";
import { getSiteSettings } from "../../lib/site-settings";
import { cleanText, digest, fail, HttpError, jsonBody, rateLimit, sameOrigin } from "../../lib/security";
import { normalizePhone } from "../../lib/business";

export async function POST(request:Request){
  try{
    sameOrigin(request);const body=await jsonBody(request,20_000);if(body.consent!==true)throw new HttpError(400,"Необходимо согласие на обработку данных");
    const name=cleanText(body.name,120,true),phone=cleanText(body.phone,40,true),normalizedPhone=normalizePhone(phone),city=cleanText(body.city,120,true),comment=cleanText(body.comment??"",1200),tractorSlug=cleanText(body.tractorSlug,120,true),sourcePath=cleanText(body.sourcePath??"/finance",300,true),programId=cleanText(body.programId,100,true),downMode=body.downMode==="amount"?"amount":"percent",downValue=Number(body.downValue),months=Math.round(Number(body.months));
    if(name.length<2||!validPublicPhone(phone))throw new HttpError(400,"Укажите имя и корректный номер телефона");
    await ensureDb();const forwarded=request.headers.get("x-forwarded-for")?.split(",")[0]??"local";await rateLimit(`lease:${forwarded}`,6,900);
    const [catalog,config,{settings}]=await Promise.all([getCatalog(),getLeasingPublicConfig(),getSiteSettings()]);const tractor=catalog.find(item=>item.slug===tractorSlug);if(!tractor)throw new HttpError(400,"Модель не найдена");
    const fallback:LeaseProgram={id:"default",name:"Стандартные условия",programType:"Лизинг",currency:"KGS",termsMonths:[LEASE_MONTHS],minDownPercent:settings.downPercent,maxDownPercent:90,minDownAmount:0,downPaymentMode:"Оба варианта",markupPercent:0,annualRate:settings.annualRate??0,fixedCommission:settings.fee,commissionPercent:0,insurance:0,processingFee:0,delivery:0,includeDelivery:true,includeInsurance:false,includeCommission:true,discountOrder:"before",rounding:1,zeroPercent:(settings.annualRate??0)===0,options:[],notes:""};
    const program=config.programs.find(item=>item.id===programId)??(programId==="default"?fallback:null);if(!program)throw new HttpError(400,"Программа недоступна");const model=config.models.find(item=>item.tractorSlug===tractorSlug);if(model?.enabled===false)throw new HttpError(400,"Для этой модели программа недоступна");
    const promotion=config.promotions.find(item=>!item.tractorSlugs.length||item.tractorSlugs.includes(tractorSlug)),publishedPrice=model?.price??salePrice(tractor.price,tractor.discountPercent??0),basePrice=publishedPrice??Number(body.estimatedPrice);if(!Number.isFinite(basePrice)||basePrice<=0||basePrice>500000000)throw new HttpError(400,"Введите ориентировочную стоимость для предварительного расчёта");
    const allowedOptions=model?.options?.length?model.options:program.options,requested=Array.isArray(body.options)?body.options.map(value=>cleanText(value,120)).filter(Boolean):[],options=requested.map(option=>{const found=allowedOptions.find(item=>item.name===option);if(!found)throw new HttpError(400,"Выбрана недоступная опция");return found});
    if(months!==LEASE_MONTHS)throw new HttpError(400,"Выбран недоступный срок");const minDown=promotion?.reducedDownPercent??model?.minDownPercent??program.minDownPercent;if((downMode==="percent"&&downValue<minDown)||(downMode==="amount"&&downValue<Math.max(program.minDownAmount,basePrice*minDown/100)))throw new HttpError(400,"Первоначальный взнос ниже допустимого");
    if(!Number.isFinite(downValue)||downValue<0||(downMode==="percent"?downValue>program.maxDownPercent:downValue>basePrice*program.maxDownPercent/100))throw new HttpError(400,"Проверьте первоначальный взнос");
    const discount=model?.discount??(promotion?promotion.discountType==="percent"?basePrice*promotion.discount/100:promotion.discount:0),zeroPercent=Boolean(promotion?.zeroPercent||program.zeroPercent),result=calculateInstallment({price:basePrice,options,delivery:program.delivery,discount,downMode,downValue,months,markupPercent:model?.markupPercent??program.markupPercent,annualRate:model?.annualRate??program.annualRate,fixedCommission:model?.fixedCommission??program.fixedCommission,commissionPercent:model?.commissionPercent??program.commissionPercent,insurance:program.insurance,processingFee:program.processingFee,includeDelivery:program.includeDelivery,includeInsurance:program.includeInsurance,includeCommission:program.includeCommission,discountOrder:program.discountOrder,rounding:program.rounding,zeroPercent});
    if(model?.maxFinancing&&result.financed>model.maxFinancing)throw new HttpError(400,"Сумма превышает лимит финансирования этой модели");
    const key=cleanText(request.headers.get("idempotency-key")??"",100,true),requestId=await digest(`leasing:${key}`),payloadHash=await digest(JSON.stringify({name,phone,city,comment,tractorSlug,programId,downMode,downValue,months,requested,basePrice})),db=getRawDb(),previous=await db.prepare("SELECT payload_hash,lead_id FROM lead_requests WHERE id=?").bind(requestId).first<{payload_hash:string;lead_id:string}>();if(previous){if(previous.payload_hash!==payloadHash)throw new HttpError(409,"Заявка уже отправлена с другими данными");return Response.json({id:previous.lead_id,duplicate:true})}
    const applicationId=crypto.randomUUID(),leadId=crypto.randomUUID(),proposedCustomerId=crypto.randomUUID(),dealId=crypto.randomUUID(),assignee=await db.prepare("SELECT id FROM staff WHERE role IN ('owner','director') AND active=1 ORDER BY CASE role WHEN 'owner' THEN 0 ELSE 1 END,created_at LIMIT 1").first<{id:string}>(),submittedAt=new Date().toISOString(),leaseData={phone,city,tractorModel:`Changfa ${tractor.model}`,tractorSlug,price:basePrice,priceSource:publishedPrice?"catalog":"customer_estimate",options:options.map(item=>`${item.name}: ${item.price} сом`).join("\n"),downPayment:result.downPayment,termMonths:months,markupPercent:zeroPercent?0:(model?.markupPercent??program.markupPercent),monthlyPayment:result.monthly,total:result.contractTotal+result.downPayment,comment,source:sourcePath,submittedAt,programId,programName:program.name,zeroPercent:String(zeroPercent),discount:result.discount,financed:result.financed,overpayment:result.overpayment};
    const customer=await db.prepare(`INSERT INTO crm_customers(id,name,phone,normalized_phone,notes,region,source,tractor_slug,budget_minor,purchase_method,assigned_to)
      VALUES(?,?,?,?,?,?,'leasing-calculator',?,?,?,?) ON CONFLICT(normalized_phone) WHERE normalized_phone IS NOT NULL AND normalized_phone<>'' AND archived=0
      DO UPDATE SET phone=excluded.phone,region=CASE WHEN excluded.region<>'' THEN excluded.region ELSE crm_customers.region END,updated_at=CURRENT_TIMESTAMP,version=crm_customers.version+1 RETURNING id`)
      .bind(proposedCustomerId,name,phone,normalizedPhone,comment,city,tractor.slug,Math.round((result.contractTotal+result.downPayment)*100),program.programType,assignee?.id??null).first<{id:string}>();
    if(!customer)throw new HttpError(500,"Не удалось связать клиента");const customerId=customer.id;Object.assign(leaseData,{customerId,dealId,partnerName:program.name,partnerDecision:"pending",documentStatus:"incomplete",requiredDocuments:"passport,income"});
    const statements=[
      db.prepare("INSERT INTO admin_records(id,kind,title,subtitle,status,category,sort_order,data_json) VALUES(?,'leasing_applications',?,?,'new','Лизинг и рассрочка',0,?)").bind(applicationId,`${name} · Changfa ${tractor.model}`,`${phone} · ${city}`,JSON.stringify(leaseData)),
      db.prepare("INSERT INTO leads(id,tractor_slug,tractor_model,name,phone,normalized_phone,customer_id,message,source,consent_version,consent_at,source_path) VALUES(?,?,?,?,?,?,?,?,'leasing-calculator','2026-09',?,?)").bind(leadId,tractor.slug,tractor.model,name,phone,normalizedPhone,customerId,comment,submittedAt,sourcePath),
      db.prepare("INSERT INTO crm_deals(id,lead_id,customer_id,title,tractor_slug,amount_minor,assigned_to) VALUES(?,?,?,?,?,?,?)").bind(dealId,leadId,customerId,`Лизинг: Changfa ${tractor.model}`,tractor.slug,Math.round((result.contractTotal+result.downPayment)*100),assignee?.id??null),
      db.prepare("INSERT INTO leasing_cases_v2(id,customer_id,deal_id,status,partner_name,partner_decision,document_status,required_documents_json,calculation_json,created_by,updated_by) VALUES(?,?,?,'new',?,'pending','incomplete',?,?,?,?)").bind(applicationId,customerId,dealId,program.name,JSON.stringify(["passport","income"]),JSON.stringify(leaseData),assignee?.id??null,assignee?.id??null),
      db.prepare("INSERT INTO lead_requests(id,payload_hash,lead_id) VALUES(?,?,?)").bind(requestId,payloadHash,leadId),
    ];
    if(assignee?.id){statements.push(db.prepare("INSERT INTO crm_tasks(id,deal_id,customer_id,title,description,priority,assigned_to,due_at) VALUES(?,?,?,'Проверить заявку на лизинг','Уточнить пакет документов и подтвердить расчёт','high',?,?)").bind(crypto.randomUUID(),dealId,customerId,assignee.id,new Date(Date.now()+60*60_000).toISOString()));statements.push(db.prepare("INSERT INTO notifications_v2(id,recipient_id,type,priority,title,body,entity_type,entity_id,target_url) VALUES(?,?,'leasing_application','high',?,?,'deal',?,'/admin/marketing/leasing-applications')").bind(crypto.randomUUID(),assignee.id,`Заявка на лизинг: ${name}`,`Changfa ${tractor.model}`,dealId));}
    try{await db.batch(statements)}catch(error){const raced=await db.prepare("SELECT payload_hash,lead_id FROM lead_requests WHERE id=?").bind(requestId).first<{payload_hash:string;lead_id:string}>();if(raced?.payload_hash===payloadHash)return Response.json({id:raced.lead_id,duplicate:true});throw error;}
    return Response.json({id:applicationId,dealId},{status:201});
  }catch(error){return fail(error)}
}
