import { ensureDb, getRawDb } from "../../../db";
import { getCatalog } from "../../lib/catalog";
import { calculateInstallment, salePrice, type LeaseProgram } from "../../lib/leasing";
import { getLeasingPublicConfig } from "../../lib/leasing-public";
import { getSiteSettings } from "../../lib/site-settings";
import { cleanText, digest, fail, HttpError, jsonBody, rateLimit, sameOrigin } from "../../lib/security";

export async function POST(request:Request){
  try{
    sameOrigin(request);const body=await jsonBody(request,20_000);if(body.consent!==true)throw new HttpError(400,"Необходимо согласие на обработку данных");
    const name=cleanText(body.name,120,true),phone=cleanText(body.phone,40,true),city=cleanText(body.city,120,true),comment=cleanText(body.comment??"",1200),tractorSlug=cleanText(body.tractorSlug,120,true),sourcePath=cleanText(body.sourcePath??"/finance",300,true),programId=cleanText(body.programId,100,true),downMode=body.downMode==="amount"?"amount":"percent",downValue=Number(body.downValue),months=Math.round(Number(body.months));
    if(name.length<2||phone.replace(/\D/g,"").length<8)throw new HttpError(400,"Укажите имя и корректный номер телефона");
    await ensureDb();const forwarded=request.headers.get("x-forwarded-for")?.split(",")[0]??"local";await rateLimit(`lease:${forwarded}`,6,900);
    const [catalog,config,{settings}]=await Promise.all([getCatalog(),getLeasingPublicConfig(),getSiteSettings()]);const tractor=catalog.find(item=>item.slug===tractorSlug);if(!tractor)throw new HttpError(400,"Модель не найдена");
    const fallback:LeaseProgram={id:"default",name:"Стандартные условия",programType:"Лизинг",currency:"KGS",termsMonths:[12,24,36,48,60],minDownPercent:settings.downPercent,maxDownPercent:90,minDownAmount:0,downPaymentMode:"Оба варианта",markupPercent:0,annualRate:settings.annualRate??0,fixedCommission:settings.fee,commissionPercent:0,insurance:0,processingFee:0,delivery:0,includeDelivery:true,includeInsurance:false,includeCommission:true,discountOrder:"before",rounding:1,zeroPercent:(settings.annualRate??0)===0,options:[],notes:""};
    const program=config.programs.find(item=>item.id===programId)??(programId==="default"?fallback:null);if(!program)throw new HttpError(400,"Программа недоступна");const model=config.models.find(item=>item.tractorSlug===tractorSlug);if(model?.enabled===false)throw new HttpError(400,"Для этой модели программа недоступна");
    const promotion=config.promotions.find(item=>!item.tractorSlugs.length||item.tractorSlugs.includes(tractorSlug)),basePrice=model?.price??salePrice(tractor.price,tractor.discountPercent??0);if(!basePrice)throw new HttpError(400,"Цена модели пока не опубликована");
    const allowedOptions=model?.options?.length?model.options:program.options,requested=Array.isArray(body.options)?body.options.map(value=>cleanText(value,120)).filter(Boolean):[],options=requested.map(option=>{const found=allowedOptions.find(item=>item.name===option);if(!found)throw new HttpError(400,"Выбрана недоступная опция");return found});
    const availableTerms=model?.termsMonths?.length?model.termsMonths:program.termsMonths;if(!availableTerms.includes(months))throw new HttpError(400,"Выбран недоступный срок");const minDown=promotion?.reducedDownPercent??model?.minDownPercent??program.minDownPercent;if((downMode==="percent"&&downValue<minDown)||(downMode==="amount"&&downValue<program.minDownAmount))throw new HttpError(400,"Первоначальный взнос ниже допустимого");
    const discount=model?.discount??(promotion?promotion.discountType==="percent"?basePrice*promotion.discount/100:promotion.discount:0),zeroPercent=Boolean(promotion?.zeroPercent||program.zeroPercent),result=calculateInstallment({price:basePrice,options,delivery:program.delivery,discount,downMode,downValue,months,markupPercent:model?.markupPercent??program.markupPercent,annualRate:model?.annualRate??program.annualRate,fixedCommission:model?.fixedCommission??program.fixedCommission,commissionPercent:model?.commissionPercent??program.commissionPercent,insurance:program.insurance,processingFee:program.processingFee,includeDelivery:program.includeDelivery,includeInsurance:program.includeInsurance,includeCommission:program.includeCommission,discountOrder:program.discountOrder,rounding:program.rounding,zeroPercent});
    if(model?.maxFinancing&&result.financed>model.maxFinancing)throw new HttpError(400,"Сумма превышает лимит финансирования этой модели");
    const key=cleanText(request.headers.get("idempotency-key")??"",100,true),requestId=await digest(`leasing:${key}`),payloadHash=await digest(JSON.stringify({name,phone,tractorSlug,programId,downMode,downValue,months,requested})),db=getRawDb(),previous=await db.prepare("SELECT payload_hash,lead_id FROM lead_requests WHERE id=?").bind(requestId).first<{payload_hash:string;lead_id:string}>();if(previous){if(previous.payload_hash!==payloadHash)throw new HttpError(409,"Заявка уже отправлена с другими данными");return Response.json({id:previous.lead_id,duplicate:true})}
    const applicationId=crypto.randomUUID(),leadId=crypto.randomUUID(),customerId=crypto.randomUUID(),dealId=crypto.randomUUID(),assignee=await db.prepare("SELECT id FROM staff WHERE role IN ('owner','director') AND active=1 ORDER BY CASE role WHEN 'owner' THEN 0 ELSE 1 END,created_at LIMIT 1").first<{id:string}>(),submittedAt=new Date().toISOString(),leaseData={phone,city,tractorModel:`Changfa ${tractor.model}`,tractorSlug,price:basePrice,options:options.map(item=>`${item.name}: ${item.price} сом`).join("\n"),downPayment:result.downPayment,termMonths:months,markupPercent:zeroPercent?0:(model?.markupPercent??program.markupPercent),monthlyPayment:result.monthly,total:result.contractTotal,comment,source:sourcePath,submittedAt,programId,programName:program.name,zeroPercent:String(zeroPercent),discount:result.discount,financed:result.financed,overpayment:result.overpayment};
    await db.batch([
      db.prepare("INSERT INTO admin_records(id,kind,title,subtitle,status,category,sort_order,data_json) VALUES(?,'leasing_applications',?,?,'new','Лизинг и рассрочка',0,?)").bind(applicationId,`${name} · Changfa ${tractor.model}`,`${phone} · ${city}`,JSON.stringify(leaseData)),
      db.prepare("INSERT INTO leads(id,tractor_slug,tractor_model,name,phone,message,source,consent_version,consent_at,source_path) VALUES(?,?,?,?,?,?,'leasing-calculator','2026-09',?,?)").bind(leadId,tractor.slug,tractor.model,name,phone,comment,submittedAt,sourcePath),
      db.prepare("INSERT INTO crm_customers(id,name,phone,notes,region,source,tractor_slug,budget_minor,purchase_method,assigned_to) VALUES(?,?,?,?,?,'leasing-calculator',?,?,?,?)").bind(customerId,name,phone,comment,city,tractor.slug,Math.round(result.contractTotal*100),program.programType,assignee?.id??null),
      db.prepare("INSERT INTO crm_deals(id,lead_id,customer_id,title,tractor_slug,amount_minor,assigned_to) VALUES(?,?,?,?,?,?,?)").bind(dealId,leadId,customerId,`Лизинг: Changfa ${tractor.model}`,tractor.slug,Math.round(result.contractTotal*100),assignee?.id??null),
      db.prepare("INSERT INTO lead_requests(id,payload_hash,lead_id) VALUES(?,?,?)").bind(requestId,payloadHash,leadId),
    ]);
    return Response.json({id:applicationId,dealId},{status:201});
  }catch(error){return fail(error)}
}
