"use client";

import { Bell, CheckSquare, FolderKanban, MessageCircleMore, Send, ShieldCheck, UserRound } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Staff={id:string;display_name:string;email:string;role:string;avatar:string|null};
type Row={id:string;title:string;subtitle:string;created_at:string;created_by:string;data:Record<string,unknown>};
type Data={actor:{id:string;display_name:string};staff:Staff[];groups:Row[];messages:Row[];notifications:{leads:Array<Record<string,unknown>>;tasks:Array<Record<string,unknown>>;audit:Array<Record<string,unknown>>}};
export type CollaborationMode="notifications"|"chat"|"groups";
const date=(value:unknown)=>new Date(String(value)).toLocaleString("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});

export function AdminCollaboration({mode}:{mode:CollaborationMode}){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[target,setTarget]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/admin/collaboration",{cache:"no-store"});const body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"Не удалось загрузить раздел");setData(body)},[]);
  useEffect(()=>{let cancelled=false;fetch("/api/admin/collaboration",{cache:"no-store"}).then(async response=>{const body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"Не удалось загрузить раздел");if(!cancelled)setData(body)}).catch(cause=>{if(!cancelled)setError(cause instanceof Error?cause.message:"Ошибка загрузки")});return()=>{cancelled=true}},[]);
  async function action(payload:Record<string,unknown>){setBusy(true);setError("");const response=await fetch("/api/admin/collaboration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json() as {error?:string};setBusy(false);if(!response.ok){setError(body.error||"Не удалось сохранить");return false}await load();return true}
  const staffById=useMemo(()=>new Map(data?.staff.map(person=>[person.id,person.display_name])??[]),[data]);
  if(!data)return <div className="admin-content"><section className="admin-panel admin-empty"><MessageCircleMore/><h3>{error||"Загружаем совместную работу…"}</h3></section></div>;
  if(mode==="notifications"){
    const items=[...data.notifications.leads.map(item=>({id:String(item.id),kind:"CRM",title:`Новая заявка: ${item.name||"клиент"}`,text:[item.phone,item.tractor_slug].filter(Boolean).join(" · "),at:item.created_at,icon:MessageCircleMore})),...data.notifications.tasks.map(item=>({id:String(item.id),kind:"Задачи",title:String(item.title),text:item.done?"Выполнено":`Срок: ${date(item.due_at)}`,at:item.due_at,icon:CheckSquare})),...data.notifications.audit.map(item=>({id:String(item.id),kind:"Система",title:String(item.action),text:String(item.detail||item.display_name||"Изменение данных"),at:item.created_at,icon:ShieldCheck}))].sort((a,b)=>new Date(String(b.at)).getTime()-new Date(String(a.at)).getTime()).slice(0,100);
    return <div className="admin-content"><section className="admin-panel collaboration-panel"><div className="panel-head"><div><span>Единый центр</span><h2>Уведомления</h2><p>CRM, задачи и изменения системы собраны по папкам.</p></div><b>{items.length}</b></div><div className="notification-folders">{["CRM","Задачи","Система"].map(kind=><span key={kind}>{kind}<b>{items.filter(item=>item.kind===kind).length}</b></span>)}</div><div className="notification-list">{items.map(item=>{const Icon=item.icon;return <article key={`${item.kind}-${item.id}`}><i><Icon/></i><div><small>{item.kind}</small><strong>{item.title}</strong><p>{item.text}</p></div><time>{date(item.at)}</time></article>})}</div></section></div>;
  }
  if(mode==="groups")return <div className="admin-content collaboration-grid"><section className="admin-panel collaboration-panel"><div className="panel-head"><div><span>Проекты</span><h2>Рабочие группы</h2><p>Соберите нужных сотрудников вокруг проекта или клиента.</p></div><FolderKanban/></div><div className="group-list">{data.groups.map(group=>{const members=Array.isArray(group.data.members)?group.data.members as string[]:[];return <article key={group.id}><i><FolderKanban/></i><div><h3>{group.title}</h3><p>{String(group.data.description||group.subtitle||"Без описания")}</p><small>{members.map(id=>staffById.get(id)||"Сотрудник").join(" · ")}</small></div></article>})}{!data.groups.length?<p>Групп пока нет.</p>:null}</div></section><GroupForm staff={data.staff} busy={busy} submit={action}/></div>;
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,f=new FormData(form),isGroup=String(target).startsWith("group:");if(await action({action:"send_message",text:f.get("text"),to:isGroup?"":target,groupId:isGroup?target.slice(6):""}))form.reset()}
  return <div className="admin-content"><section className="admin-panel collaboration-panel chat-panel"><div className="panel-head"><div><span>Команда ATADAN</span><h2>Чат сотрудников</h2><p>Личные сообщения и группы в одном рабочем потоке.</p></div><Bell/></div><label className="chat-target"><span>Кому написать</span><select value={target} onChange={event=>setTarget(event.target.value)} required><option value="">Выберите получателя</option><optgroup label="Сотрудники">{data.staff.filter(person=>person.id!==data.actor.id).map(person=><option value={person.id} key={person.id}>{person.display_name} · {person.role}</option>)}</optgroup><optgroup label="Группы">{data.groups.map(group=><option value={`group:${group.id}`} key={group.id}>{group.title}</option>)}</optgroup></select></label><div className="chat-feed">{data.messages.toReversed().map(message=><article className={message.created_by===data.actor.id?"mine":""} key={message.id}><small>{String(message.data.fromName||staffById.get(message.created_by)||"Сотрудник")}</small><p>{String(message.data.text||message.subtitle)}</p><time>{date(message.created_at)}</time></article>)}</div><form className="chat-compose" onSubmit={send}><textarea name="text" rows={3} maxLength={4000} placeholder="Напишите сообщение…" required/><button className="admin-primary" type="submit" disabled={busy||!target}><Send/>Отправить</button></form>{error?<p className="form-error" role="alert">{error}</p>:null}</section></div>;
}

function GroupForm({staff,busy,submit}:{staff:Staff[];busy:boolean;submit:(payload:Record<string,unknown>)=>Promise<boolean>}){async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,f=new FormData(form);if(await submit({action:"create_group",title:f.get("title"),description:f.get("description"),members:f.getAll("members")}))form.reset()}return <form className="admin-panel group-form" onSubmit={save}><div><span>Новая группа</span><h2>Собрать команду</h2></div><label><span>Название</span><input name="title" required maxLength={120}/></label><label><span>Описание или проект</span><textarea name="description" rows={3}/></label><fieldset><legend>Участники</legend>{staff.map(person=><label key={person.id}><input type="checkbox" name="members" value={person.id}/><UserRound/><span>{person.display_name}<small>{person.role}</small></span></label>)}</fieldset><button className="admin-primary" disabled={busy} type="submit"><FolderKanban/>Создать группу</button></form>}
