"use client";

import { Archive, Check, ChevronLeft, ChevronRight, Database, FilePenLine, Filter, LoaderCircle, Plus, Search, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";

export type RecordKind =
  | "home_sections" | "categories" | "promotions" | "parts" | "attachments" | "gallery" | "reviews" | "faq" | "branches" | "leasing_terms" | "service_pages"
  | "reservations" | "sales" | "inventory_units" | "stock_parts" | "stock_attachments" | "stock_movements" | "suppliers" | "purchases" | "shipments" | "finance_entries"
  | "debts" | "installments" | "payroll" | "documents" | "service_cases" | "manager_plans" | "meetings" | "payments";

type Field = { key:string; label:string; type?:"text"|"number"|"date"|"url"|"textarea"|"select"; options?:string[]; required?:boolean; hint?:string };
type ModuleConfig = { title:string; description:string; singular:string; fields:Field[]; statuses?:string[] };

const configs:Record<RecordKind,ModuleConfig> = {
  home_sections:{title:"Главная и баннеры",description:"Заголовки, описания, кнопки, изображения и порядок блоков публичной главной.",singular:"блок",fields:[{key:"buttonLabel",label:"Текст кнопки"},{key:"buttonUrl",label:"Ссылка кнопки"},{key:"desktopImage",label:"Баннер для компьютера",type:"url"},{key:"tabletImage",label:"Баннер для планшета",type:"url"},{key:"mobileImage",label:"Баннер для телефона",type:"url"}]},
  categories:{title:"Категории",description:"Самостоятельная структура каталога без смешения с карточками техники.",singular:"категорию",fields:[{key:"slug",label:"Slug",required:true},{key:"description",label:"Описание",type:"textarea"}]},
  promotions:{title:"Акции",description:"Сроки, выгода и привязка специальных предложений к моделям.",singular:"акцию",fields:[{key:"discount",label:"Скидка, %",type:"number"},{key:"startsAt",label:"Начало",type:"date"},{key:"endsAt",label:"Окончание",type:"date"},{key:"tractorSlugs",label:"Модели — slug через запятую"},{key:"terms",label:"Условия",type:"textarea"}]},
  parts:{title:"Запчасти",description:"Отдельный публичный ассортимент запасных частей.",singular:"запчасть",fields:[{key:"sku",label:"Артикул",required:true},{key:"price",label:"Цена, сом",type:"number"},{key:"stock",label:"Остаток",type:"number"},{key:"compatibleModels",label:"Совместимые модели"},{key:"image",label:"Изображение",type:"url"}]},
  attachments:{title:"Навесное оборудование",description:"Оборудование и совместимость с тракторами Changfa.",singular:"оборудование",fields:[{key:"sku",label:"Артикул"},{key:"price",label:"Цена, сом",type:"number"},{key:"stock",label:"Остаток",type:"number"},{key:"compatibleModels",label:"Совместимые модели"},{key:"image",label:"Изображение",type:"url"}]},
  gallery:{title:"Галерея",description:"Фотографии, подписи и порядок показа на сайте.",singular:"фотографию",fields:[{key:"image",label:"Изображение",type:"url",required:true},{key:"caption",label:"Подпись"},{key:"alt",label:"Описание для доступности"}]},
  reviews:{title:"Отзывы",description:"Публикуются только подтверждённые отзывы реальных клиентов.",singular:"отзыв",fields:[{key:"author",label:"Имя клиента",required:true},{key:"company",label:"Хозяйство"},{key:"tractorModel",label:"Модель"},{key:"quote",label:"Текст отзыва",type:"textarea",required:true},{key:"verifiedBy",label:"Кем подтверждён"}]},
  faq:{title:"Чатбот · Частые вопросы",description:"Опубликованные вопросы сразу появляются в помощнике ATADAN на публичном сайте. Их можно менять, скрывать и переставлять.",singular:"вопрос",fields:[{key:"question",label:"Вопрос посетителя",required:true},{key:"answer",label:"Понятный ответ",type:"textarea",required:true},{key:"buttonLabel",label:"Текст ссылки"},{key:"buttonUrl",label:"Ссылка",type:"url"}]},
  branches:{title:"Контакты и филиалы",description:"Адреса, телефоны, график работы, карта и ответственные.",singular:"филиал",fields:[{key:"address",label:"Адрес",required:true},{key:"phone",label:"Телефон",required:true},{key:"hours",label:"График работы"},{key:"mapUrl",label:"Ссылка на карту",type:"url"},{key:"manager",label:"Ответственный"}]},
  leasing_terms:{title:"Лизинг и рассрочка",description:"Условия финансирования: ставка, первый взнос, срок и пояснение для клиента.",singular:"условие",fields:[{key:"rate",label:"Ставка, %",type:"number"},{key:"downPayment",label:"Первоначальный взнос, %",type:"number"},{key:"termMonths",label:"Срок, месяцев",type:"number"},{key:"fee",label:"Комиссия, сом",type:"number"},{key:"partner",label:"Финансовый партнёр"},{key:"buttonUrl",label:"Ссылка на заявку",type:"url"},{key:"notes",label:"Пояснения",type:"textarea"}]},
  service_pages:{title:"Сервис",description:"Публикации о диагностике, обслуживании и запчастях. После статуса «Опубликовано» карточка появляется на странице сервиса.",singular:"сервисный материал",fields:[{key:"slug",label:"Адрес страницы (slug)",required:true,hint:"Только латинские буквы, цифры и дефисы: diagnostika-changfa"},{key:"fullText",label:"Полный текст",type:"textarea",required:true},{key:"cover",label:"Главное изображение",type:"url",required:true},{key:"imageAlt",label:"Описание изображения"},{key:"gallery",label:"Галерея — ссылки по одной на строку",type:"textarea"},{key:"video",label:"Ссылка на видео",type:"url"},{key:"works",label:"Что входит — по одному пункту на строку",type:"textarea"},{key:"conditions",label:"Условия",type:"textarea"},{key:"timing",label:"Срок выполнения"},{key:"price",label:"Стоимость или «по запросу"},{key:"relatedModels",label:"Связанные модели"},{key:"contacts",label:"Телефон сервиса"},{key:"buttonLabel",label:"Текст дополнительной ссылки"},{key:"buttonUrl",label:"Дополнительная ссылка",type:"url"},{key:"publishDate",label:"Дата публикации",type:"date"},{key:"seoTitle",label:"SEO title"},{key:"seoDescription",label:"SEO description",type:"textarea"}]},
  reservations:{title:"Бронирования",description:"Брони техники с клиентом, сроком и ответственным.",singular:"бронь",fields:[{key:"dealId",label:"ID сделки"},{key:"customer",label:"Клиент",required:true},{key:"tractorVin",label:"VIN / серийный номер",required:true},{key:"expiresAt",label:"Действует до",type:"date"},{key:"amount",label:"Сумма брони, сом",type:"number"}]},
  sales:{title:"Продажи",description:"Успешные сделки появляются здесь автоматически. Ручную продажу можно добавить этой же кнопкой.",singular:"продажу",fields:[{key:"dealId",label:"ID сделки"},{key:"customer",label:"Клиент",required:true},{key:"phone",label:"Телефон"},{key:"tractorModel",label:"Модель трактора",required:true},{key:"tractorVin",label:"VIN / серийный номер"},{key:"salePrice",label:"Цена продажи, сом",type:"number",required:true},{key:"costPrice",label:"Себестоимость, сом",type:"number"},{key:"saleDate",label:"Дата продажи",type:"date"},{key:"manager",label:"Менеджер"},{key:"paymentMethod",label:"Способ оплаты"}]},
  inventory_units:{title:"Склад",description:"Каждая физическая единица: VIN, модель, статус, себестоимость и будущая цена продажи. При успешной сделке подходящая единица отмечается проданной автоматически.",singular:"единицу техники",fields:[{key:"vin",label:"VIN / серийный номер",required:true},{key:"model",label:"Модель",required:true},{key:"tractorSlug",label:"Slug модели из каталога",required:true,hint:"Например: cfk2404-g4 — это связывает склад со сделками"},{key:"unitStatus",label:"Статус",type:"select",options:["Заказан","Производство","В пути","Таможня","На складе","Забронирован","Продан","Выдан"]},{key:"purchaseCost",label:"Себестоимость, сом",type:"number",required:true},{key:"expenses",label:"Дополнительные расходы, сом",type:"number"},{key:"salePrice",label:"Цена продажи, сом",type:"number",required:true},{key:"location",label:"Местонахождение"},{key:"customer",label:"Клиент"}]},
  stock_parts:{title:"Склад запчастей",description:"Остатки и резервы запасных частей.",singular:"складскую позицию",fields:[{key:"sku",label:"Артикул",required:true},{key:"quantity",label:"Остаток",type:"number"},{key:"reserved",label:"В резерве",type:"number"},{key:"location",label:"Место хранения"}]},
  stock_attachments:{title:"Склад оборудования",description:"Остатки и резервы навесного оборудования.",singular:"складскую позицию",fields:[{key:"sku",label:"Артикул",required:true},{key:"quantity",label:"Остаток",type:"number"},{key:"reserved",label:"В резерве",type:"number"},{key:"location",label:"Место хранения"}]},
  stock_movements:{title:"Движения склада",description:"Приход, расход, перемещение и резерв.",singular:"движение",fields:[{key:"movementType",label:"Тип",type:"select",options:["Приход","Расход","Перемещение","Резерв","Снятие резерва"]},{key:"skuOrVin",label:"Артикул / VIN",required:true},{key:"quantity",label:"Количество",type:"number"},{key:"from",label:"Откуда"},{key:"to",label:"Куда"},{key:"date",label:"Дата",type:"date"}]},
  suppliers:{title:"Поставщики",description:"Поставщики и фактические партии: откуда пришло, сколько единиц, цена за штуку и общая сумма.",singular:"поставщика или поставку",fields:[{key:"company",label:"Компания-поставщик",required:true},{key:"contact",label:"Контактное лицо"},{key:"phone",label:"Телефон"},{key:"email",label:"Email"},{key:"country",label:"Страна / откуда"},{key:"products",label:"Модели или товар",type:"textarea"},{key:"quantity",label:"Количество, шт.",type:"number",required:true},{key:"unitPrice",label:"Цена за единицу, сом",type:"number",required:true},{key:"total",label:"Общая сумма, сом",type:"number",hint:"Можно сверить: количество × цена за единицу"},{key:"deliveryDate",label:"Дата поставки",type:"date"},{key:"terms",label:"Условия и комментарий",type:"textarea"}]},
  purchases:{title:"Закупки",description:"Заказы производителю и закупочные документы.",singular:"закупку",fields:[{key:"supplier",label:"Поставщик",required:true},{key:"orderNumber",label:"Номер заказа"},{key:"amount",label:"Сумма, сом",type:"number"},{key:"orderDate",label:"Дата заказа",type:"date"},{key:"expectedAt",label:"Ожидается",type:"date"}]},
  shipments:{title:"Поставки и логистика",description:"Маршрут, этап и плановая дата прибытия.",singular:"поставку",fields:[{key:"orderNumber",label:"Номер заказа"},{key:"route",label:"Маршрут"},{key:"transport",label:"Транспорт"},{key:"eta",label:"Ожидаемая дата",type:"date"},{key:"tracking",label:"Отслеживание"}]},
  finance_entries:{title:"Расходы",description:"Все затраты компании по понятным категориям: аренда, свет, вода, питание, транспорт и другие минусы.",singular:"расход",fields:[{key:"type",label:"Тип операции",type:"select",options:["Расход"]},{key:"expenseCategory",label:"Категория",type:"select",options:["Аренда","Электричество","Вода","Питание","Транспорт","Маркетинг","Зарплата","Сервис","Налоги","Другое"]},{key:"amount",label:"Сумма, сом",type:"number",required:true},{key:"date",label:"Дата",type:"date",required:true},{key:"counterparty",label:"Кому оплачено"},{key:"paymentMethod",label:"Способ оплаты"},{key:"document",label:"Документ / чек"},{key:"notes",label:"Комментарий",type:"textarea"}]},
  debts:{title:"Задолженности",description:"Долги клиентов и обязательства компании.",singular:"задолженность",fields:[{key:"direction",label:"Тип",type:"select",options:["Нам должны","Мы должны"]},{key:"counterparty",label:"Контрагент",required:true},{key:"amount",label:"Сумма, сом",type:"number"},{key:"dueAt",label:"Срок",type:"date"}]},
  installments:{title:"Рассрочки",description:"Внутренний график платежей по договорам.",singular:"рассрочку",fields:[{key:"customer",label:"Клиент",required:true},{key:"contract",label:"Договор"},{key:"total",label:"Общая сумма, сом",type:"number"},{key:"paid",label:"Оплачено, сом",type:"number"},{key:"nextPayment",label:"Следующий платёж",type:"date"}]},
  payroll:{title:"Зарплаты и бонусы",description:"Начисления сотрудникам по периодам.",singular:"начисление",fields:[{key:"employee",label:"Сотрудник",required:true},{key:"period",label:"Период"},{key:"salary",label:"Оклад, сом",type:"number"},{key:"bonus",label:"Бонус, сом",type:"number"}]},
  documents:{title:"Договоры и документы",description:"Реестр документов с привязкой к клиентам и сделкам.",singular:"документ",fields:[{key:"documentType",label:"Тип документа"},{key:"number",label:"Номер"},{key:"customer",label:"Клиент"},{key:"dealId",label:"ID сделки"},{key:"fileUrl",label:"Файл",type:"url"},{key:"date",label:"Дата",type:"date"}]},
  service_cases:{title:"Сервис и гарантия",description:"Внутренняя история ТО и ремонта по VIN.",singular:"сервисный случай",fields:[{key:"customer",label:"Клиент",required:true},{key:"vin",label:"VIN",required:true},{key:"tractor",label:"Трактор"},{key:"serviceType",label:"ТО / ремонт / гарантия"},{key:"engineHours",label:"Моточасы",type:"number"},{key:"partsUsed",label:"Использованные запчасти",type:"textarea"},{key:"workDone",label:"Выполненные работы",type:"textarea"},{key:"date",label:"Дата",type:"date"}]},
  manager_plans:{title:"Планы менеджеров",description:"План продаж и выручки по сотрудникам.",singular:"план",fields:[{key:"manager",label:"Менеджер",required:true},{key:"period",label:"Период"},{key:"salesPlan",label:"План продаж",type:"number"},{key:"revenuePlan",label:"План выручки, сом",type:"number"}]},
  meetings:{title:"Встречи",description:"Встречи, результат и следующий шаг.",singular:"встречу",fields:[{key:"customer",label:"Клиент",required:true},{key:"dealId",label:"ID сделки"},{key:"date",label:"Дата",type:"date"},{key:"result",label:"Результат",type:"textarea"},{key:"nextStep",label:"Следующий шаг"}]},
  payments:{title:"Платежи",description:"Поступления по клиентам и сделкам.",singular:"платёж",fields:[{key:"customer",label:"Клиент",required:true},{key:"dealId",label:"ID сделки"},{key:"amount",label:"Сумма, сом",type:"number"},{key:"date",label:"Дата",type:"date"},{key:"method",label:"Способ оплаты"}]},
};

type AdminRecord = { id:string;kind:RecordKind;title:string;subtitle:string;status:string;category:string;sort_order:number;data_json:string;version:number;updated_at:string };
const statusLabels:Record<string,string>={draft:"Черновик",published:"Опубликовано",hidden:"Скрыто",active:"Активно",closed:"Закрыто",archived:"Архив"};

export function AdminRecordsManager({ kind }: { kind:RecordKind }) {
  const config=configs[kind];
  const [records,setRecords]=useState<AdminRecord[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[sort,setSort]=useState("order"),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[editing,setEditing]=useState<AdminRecord|null|"new">(null);
  const pageSize=12;
  const load=useCallback(async()=>{setLoading(true);const params=new URLSearchParams({kind,page:String(page),pageSize:String(pageSize),q:query,status,sort});const response=await fetch(`/api/admin/records?${params}`,{cache:"no-store"});const result=await response.json().catch(()=>({})) as {records?:AdminRecord[];total?:number;error?:string};setLoading(false);if(!response.ok){setMessage(result.error||"Не удалось загрузить данные");return;}setRecords(result.records??[]);setTotal(result.total??0);},[kind,page,query,status,sort]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const pages=Math.max(1,Math.ceil(total/pageSize));
  async function mutate(payload:Record<string,unknown>){setLoading(true);const response=await fetch("/api/admin/records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,...payload})});const result=await response.json().catch(()=>({})) as {error?:string};setLoading(false);setMessage(response.ok?"Изменения сохранены":result.error||"Не удалось сохранить");if(response.ok){setEditing(null);await load();}return response.ok;}
  return <div className="admin-content admin-records"><section className="admin-panel records-intro"><div><span>Рабочий модуль</span><h2>{config.title}</h2><p>{config.description}</p></div><button type="button" className="admin-primary" onClick={()=>setEditing("new")}><Plus/>Добавить {config.singular}</button></section>
    <section className="admin-panel records-panel"><div className="records-toolbar"><label><Search/><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Поиск по названию, описанию или категории" aria-label="Поиск"/></label><label><Filter/><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}} aria-label="Фильтр статуса"><option value="all">Все статусы</option>{["draft","published","hidden","active","closed"].map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select></label><select value={sort} onChange={event=>{setSort(event.target.value);setPage(1)}} aria-label="Сортировка"><option value="order">По порядку</option><option value="title">По названию</option><option value="oldest">Сначала старые</option></select></div>
      {loading?<div className="admin-empty"><LoaderCircle className="spin"/><h3>Загружаем данные</h3></div>:records.length?<div className="records-grid">{records.map(record=><RecordCard key={record.id} record={record} edit={()=>setEditing(record)} status={value=>void mutate({action:"status",id:record.id,version:record.version,status:value})} remove={()=>confirm(`Перенести «${record.title}» в архив?`)&&void mutate({action:"delete",id:record.id,version:record.version})}/>)}</div>:<div className="admin-empty"><Database/><h3>Записей пока нет</h3><p>Добавьте первую запись — она сохранится в общей SQL-базе.</p><button type="button" onClick={()=>setEditing("new")}><Plus/>Добавить {config.singular}</button></div>}
      <footer className="records-pagination"><span>Показано {records.length} из {total}</span><div><button type="button" disabled={page<=1} onClick={()=>setPage(value=>value-1)} aria-label="Предыдущая страница"><ChevronLeft/></button><b>{page} / {pages}</b><button type="button" disabled={page>=pages} onClick={()=>setPage(value=>value+1)} aria-label="Следующая страница"><ChevronRight/></button></div></footer>
    </section>{message?<div className="admin-toast" role="status"><Check/>{message}<button type="button" onClick={()=>setMessage("")}><X/></button></div>:null}{editing?<RecordEditor config={config} record={editing==="new"?null:editing} close={()=>setEditing(null)} save={payload=>mutate(payload)}/>:null}</div>;
}

function dataOf(record:AdminRecord){try{return JSON.parse(record.data_json) as Record<string,unknown>}catch{return {}}}
function RecordCard({record,edit,status,remove}:{record:AdminRecord;edit:()=>void;status:(value:string)=>void;remove:()=>void}){const data=dataOf(record);const detail=String(data.vin||data.sku||data.customer||data.address||data.amount||"");const money=(value:unknown)=>`${new Intl.NumberFormat("ru-RU").format(Number(value)||0)} сом`;const facts=record.kind==="suppliers"?[["Количество",`${data.quantity||0} шт.`],["Цена / шт.",money(data.unitPrice)],["Итого",money(data.total)]]:record.kind==="inventory_units"?[["Статус",String(data.unitStatus||"Не указан")],["Себестоимость",money(data.purchaseCost)],["Цена продажи",money(data.salePrice)]]:record.kind==="sales"?[["Модель",String(data.tractorModel||"Не указана")],["Продажа",money(data.salePrice)],["Дата",String(data.saleDate||"Не указана")]]:record.kind==="finance_entries"?[["Категория",String(data.expenseCategory||"Другое")],["Сумма",money(data.amount)],["Дата",String(data.date||"Не указана")]]:[];return <article className="record-card"><header><span className={`record-status ${record.status}`}>{statusLabels[record.status]??record.status}</span><small>№ {record.sort_order}</small></header><h3>{record.title}</h3>{record.subtitle?<p>{record.subtitle}</p>:null}{record.category?<b>{record.category}</b>:null}{detail?<em>{detail}</em>:null}{facts.length?<dl className="record-metrics">{facts.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>:null}<footer><button type="button" onClick={edit}><FilePenLine/>Изменить</button><select value={record.status} onChange={event=>status(event.target.value)} aria-label={`Статус ${record.title}`}>{["draft","published","hidden","active","closed"].map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select><button className="record-delete" type="button" onClick={remove} aria-label={`Архивировать ${record.title}`}><Archive/></button></footer></article>}

function RecordEditor({config,record,close,save}:{config:ModuleConfig;record:AdminRecord|null;close:()=>void;save:(payload:Record<string,unknown>)=>Promise<boolean>}){
  const formRef=useRef<HTMLFormElement>(null),data=record?dataOf(record):{};
  useEffect(()=>{const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;const old=document.body.style.overflow;document.body.style.overflow="hidden";formRef.current?.querySelector<HTMLElement>("input,textarea,select,button")?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")close()};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=old;previous?.focus()}},[close]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const custom=Object.fromEntries(config.fields.map(field=>[field.key,String(form.get(field.key)??"")]));await save({action:record?"update":"create",id:record?.id,version:record?.version,title:String(form.get("title")),subtitle:String(form.get("subtitle")),category:String(form.get("category")),status:String(form.get("status")),sortOrder:Number(form.get("sortOrder")),data:custom});}
  return <div className="editor-overlay"><button className="editor-backdrop" type="button" onClick={close} aria-label="Закрыть редактор"/><form ref={formRef} className="record-editor" onSubmit={submit} role="dialog" aria-modal="true" aria-labelledby="record-editor-title"><header><div><span>{record?"Редактирование":"Новая запись"}</span><h2 id="record-editor-title">{config.title}</h2></div><button type="button" onClick={close} aria-label="Закрыть"><X/></button></header><div className="record-editor-body"><fieldset><legend>Основные данные</legend><label className="full"><span>Название</span><input name="title" defaultValue={record?.title??""} required/></label><label className="full"><span>Краткое описание</span><textarea name="subtitle" rows={3} defaultValue={record?.subtitle??""}/></label><label><span>Категория</span><input name="category" defaultValue={record?.category??""}/></label><label><span>Статус</span><select name="status" defaultValue={record?.status??"draft"}>{["draft","published","hidden","active","closed"].map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select></label><label><span>Порядок</span><input name="sortOrder" type="number" min="0" defaultValue={record?.sort_order??0}/></label></fieldset><fieldset><legend>Данные раздела</legend>{config.fields.map(field=><label className={field.type==="textarea"?"full":""} key={field.key}><span>{field.label}</span>{field.type==="textarea"?<textarea name={field.key} rows={5} defaultValue={String(data[field.key]??"")} required={field.required}/>:field.type==="select"?<select name={field.key} defaultValue={String(data[field.key]??field.options?.[0]??"")}>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:<input name={field.key} type={field.type??"text"} defaultValue={String(data[field.key]??"")} required={field.required}/>} {field.hint?<small>{field.hint}</small>:null}</label>)}</fieldset></div><footer><button type="button" onClick={close}>Отмена</button><button className="admin-primary" type="submit"><Check/>Сохранить</button></footer></form></div>;
}
