import { getRawDb } from "../../../../db";
import { hashPassword } from "../../../lib/admin-auth";
import { digest, fail, HttpError, jsonBody, rateLimit, sameOrigin } from "../../../lib/security";

export async function POST(request:Request){
  try{
    sameOrigin(request);const body=await jsonBody(request,5000),token=typeof body.token==="string"?body.token:"",password=typeof body.password==="string"?body.password:"";if(!/^[a-f0-9]{64}$/i.test(token))throw new HttpError(400,"Ссылка восстановления недействительна");const ip=request.headers.get("cf-connecting-ip")||request.headers.get("x-forwarded-for")?.split(",")[0]||"local";await rateLimit(`password-reset:${ip}`,10,900);const db=getRawDb(),hash=await digest(token),row=await db.prepare("SELECT staff_id FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>?").bind(hash,Math.floor(Date.now()/1000)).first<{staff_id:string}>();if(!row)throw new HttpError(410,"Ссылка истекла или уже использована");const staff=await db.prepare("SELECT role,email FROM staff WHERE id=? AND active=1").bind(row.staff_id).first<{role:string;email:string}>();if(!staff)throw new HttpError(404,"Аккаунт недоступен");if(["owner","director"].includes(staff.role)&&password.length<12)throw new HttpError(400,"Пароль должен содержать не менее 12 символов");const derived=await hashPassword(password);await db.transaction(async client=>{const used=await db.prepare("UPDATE password_reset_tokens SET used_at=CURRENT_TIMESTAMP WHERE token_hash=? AND used_at IS NULL").bind(hash).execute(client);if(!used.meta.changes)throw new HttpError(410,"Ссылка уже использована");await db.prepare("UPDATE staff SET password_hash=?,salt=? WHERE id=?").bind(derived.hash,derived.salt,row.staff_id).execute(client);await db.prepare("DELETE FROM staff_sessions WHERE staff_id=?").bind(row.staff_id).execute(client);await db.prepare("INSERT INTO auth_events(id,staff_id,identifier,event_type) VALUES(?,?,?,'password_reset')").bind(crypto.randomUUID(),row.staff_id,staff.email).execute(client);});return Response.json({ok:true});
  }catch(error){return fail(error)}
}
