import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, CalendarDays, Clock3, Phone, Wrench } from "lucide-react";
import Image from "next/image";
import { Link } from "../../components/SiteLink";
import { PageHero } from "../../components/PageHero";
import { getPublishedRecords } from "../../lib/public-records";

export const dynamic="force-dynamic";
export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const records=await getPublishedRecords("service_pages");const item=records.find(row=>(row.data.slug||row.id)===slug);if(!item)notFound();const works=(item.data.works||"").split(/\r?\n/).filter(Boolean);const gallery=(item.data.gallery||"").split(/\r?\n/).map(value=>value.trim()).filter(Boolean);return <main><PageHero image={item.data.cover||"/images/banners/service.webp"} kickerId="service.kicker" titleId="service.title" subtitleId="service.subtitle"/><article className="section-shell service-detail"><Link href="/service"><ArrowLeft/>Все материалы</Link><header><span>{item.category||"Сервис"}</span><h1>{item.title}</h1><p>{item.subtitle}</p></header><div className="service-detail-meta">{item.data.publishDate?<span><CalendarDays/>{item.data.publishDate}</span>:null}{item.data.timing?<span><Clock3/>{item.data.timing}</span>:null}{item.data.price?<span><Wrench/>{item.data.price}</span>:null}</div><div className="service-detail-copy">{item.data.fullText?.split(/\n{2,}/).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div>{gallery.length?<div className="service-detail-gallery">{gallery.map((image,index)=><span key={`${image}-${index}`}><Image src={image} alt={`${item.title} — фото ${index+1}`} fill sizes="(max-width: 720px) 100vw, 50vw"/></span>)}</div>:null}{item.data.video?<video className="service-detail-video" src={item.data.video} controls playsInline preload="metadata"><track kind="captions" src="/captions/service-ru.vtt" srcLang="ru" label="Русский"/></video>:null}{works.length?<section><h2>Что входит в работу</h2><ul>{works.map(work=><li key={work}>{work}</li>)}</ul></section>:null}{item.data.conditions?<section><h2>Условия</h2><p>{item.data.conditions}</p></section>:null}<div className="service-detail-actions"><a className="primary-btn" href={`tel:${(item.data.contacts||"+996706131404").replace(/[^+\d]/g,"")}`}><Phone/>Связаться с сервисом</a>{item.data.buttonUrl?<a className="outline-btn" href={item.data.buttonUrl} target={item.data.buttonUrl.startsWith("http")?"_blank":undefined} rel={item.data.buttonUrl.startsWith("http")?"noreferrer":undefined}>{item.data.buttonLabel||"Подробнее"}<ArrowUpRight/></a>:null}</div></article></main>}
