import { useEffect, useState } from 'react'
import { Menu, MessageCircle, X } from 'lucide-react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { Wordmark } from './Wordmark'
import { buildWhatsAppUrl } from './WhatsAppButton'
import { copy, localeFromPath, locales } from '../lib/i18n'
import { trackEvent } from '../lib/analytics'
import type { Locale } from '../lib/types'

export function Header({ phone = '996706131404' }: { phone?: string }) {
  const location = useLocation(); const navigate = useNavigate(); const locale = localeFromPath(location.pathname); const t = copy(locale)
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 28); onScroll(); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  useEffect(() => setOpen(false), [location.pathname])
  const changeLocale = (next: Locale) => { const parts = location.pathname.split('/').filter(Boolean); if (parts[0] === 'ru' || parts[0] === 'kg' || parts[0] === 'en') parts[0] = next; else parts.unshift(next); trackEvent('language_change', { locale: next, metadata: { from: locale, to: next } }); navigate('/' + parts.join('/') + location.search) }
  const nav = [{ to: `/${locale}`, label: t.home }, { to: `/${locale}/tractors`, label: t.tractors }, { to: `/${locale}#about`, label: t.about }, { to: `/${locale}#contacts`, label: t.contacts }]
  const solid = scrolled || open
  return <header className={`fixed inset-x-0 top-0 z-50 transition-all ${solid ? 'border-b border-black/5 bg-white/94 shadow-sm backdrop-blur-xl' : 'bg-transparent'}`}><div className="mx-auto flex h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-12"><Link to={`/${locale}`} aria-label="ATADAN home"><Wordmark inverse={!solid} /></Link><nav className="hidden items-center gap-7 lg:flex" aria-label="Main navigation">{nav.map((item) => <Link key={item.label} to={item.to} className={`text-sm font-semibold transition ${solid ? 'text-neutral-700 hover:text-black' : 'text-white/90 hover:text-white'}`}>{item.label}</Link>)}</nav><div className="hidden items-center gap-3 lg:flex"><div className={`flex rounded-full p-1 ${solid ? 'bg-neutral-100' : 'bg-white/15 backdrop-blur'}`}>{locales.map((l) => <button key={l} onClick={() => changeLocale(l)} className={`min-h-9 min-w-10 rounded-full px-2 text-xs font-bold uppercase ${l === locale ? 'bg-atadan-500 text-[#132208]' : solid ? 'text-neutral-500' : 'text-white/80'}`}>{l}</button>)}</div><a href={buildWhatsAppUrl(phone, 'Здравствуйте! Хочу получить консультацию по тракторам CHANGFA.')} target="_blank" rel="noreferrer" onClick={() => trackEvent('whatsapp_click', { locale, metadata: { button_location: 'header' } })} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-atadan-500 px-5 text-sm font-bold text-[#102006]"><MessageCircle size={17} /> WhatsApp</a></div><button className={`grid h-11 w-11 place-items-center rounded-full lg:hidden ${solid ? 'bg-neutral-100 text-black' : 'bg-white/15 text-white backdrop-blur'}`} onClick={() => setOpen(!open)} aria-label={open ? t.close : t.menu}>{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-black/5 bg-white px-5 pb-6 pt-4 lg:hidden"><div className="flex flex-col gap-1">{nav.map((item) => <Link key={item.label} to={item.to} className="rounded-2xl px-4 py-3 text-base font-semibold text-neutral-800 hover:bg-neutral-50">{item.label}</Link>)}</div><div className="mt-4 flex items-center justify-between gap-3"><div className="flex rounded-full bg-neutral-100 p-1">{locales.map((l) => <button key={l} onClick={() => changeLocale(l)} className={`min-h-10 min-w-12 rounded-full px-2 text-xs font-bold uppercase ${l === locale ? 'bg-atadan-500' : 'text-neutral-500'}`}>{l}</button>)}</div><a href={buildWhatsAppUrl(phone, 'Здравствуйте! Хочу получить консультацию по тракторам CHANGFA.')} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-atadan-500 px-4 text-sm font-bold"><MessageCircle size={17} /> WhatsApp</a></div></div>}</header>
}
