import { useParams } from 'react-router-dom'
import { Check, Download, MessageCircle } from 'lucide-react'
import PageHero from '../components/PageHero'
import LeasingCalculator from '../components/LeasingCalculator'
import LeadForm from '../components/LeadForm'
import { getTractor } from '../data/tractors'
import { whatsappUrl } from '../utils/helpers'
import NotFoundPage from './NotFoundPage'
export default function CommercialOfferPage(){const {slug}=useParams();const tractor=getTractor(slug);if(!tractor)return <NotFoundPage/>;return <><PageHero eyebrow="Коммерческое предложение" title={tractor.model} lead="Информационная версия предложения. Актуальную цену, комплектацию и сроки подтвердит менеджер."/><section className="section"><div className="container offer-layout"><div className="offer-product"><img src={tractor.image} alt={tractor.model}/><div><span>Стоимость</span><strong>{tractor.priceLabel||'Цена по запросу'}</strong></div></div><div className="offer-summary"><h2>Основные параметры</h2><ul><li><Check/>Мощность: {tractor.power} л.с.</li><li><Check/>Полный привод: 4×4</li><li><Check/>Коробка: {tractor.gears}</li><li><Check/>Масса: около {tractor.mass} кг</li>{tractor.pto&&<li><Check/>ВОМ: {tractor.pto}</li>}{tractor.lift&&<li><Check/>Навеска: до {tractor.lift} кг</li>}</ul><a className="btn btn-gold" href={whatsappUrl(`Здравствуйте! Пришлите актуальное коммерческое предложение на ${tractor.model}.`)} target="_blank" rel="noreferrer"><MessageCircle/>Запросить PDF у менеджера</a><p className="notice">Документ на сайте не является публичной офертой. Цена и условия могут измениться.</p></div></div></section><section className="section section-tinted"><div className="container"><div className="section-header"><span className="eyebrow">Лизинг</span><h2>Ориентировочный расчёт</h2></div><LeasingCalculator initialPrice={tractor.price||6850000}/></div></section><section className="final-cta"><div className="container final-grid"><div><span className="eyebrow light">Актуальный документ</span><h2>Получите предложение с реквизитами и сроком действия</h2></div><LeadForm source={`offer:${tractor.slug}`} compact/></div></section></>}
