import { useMemo, useState } from 'react'
import { useSearchParams, Link } from 'react-router-dom'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import PageHero from '../components/PageHero'
import TractorCard from '../components/TractorCard'
import { tractors, localize } from '../data/tractors'
import { jobOptions } from '../data/content'
import { langCode } from '../utils/helpers'
export default function SelectorPage(){
 const {i18n}=useTranslation();const lang=langCode(i18n);const [params]=useSearchParams();const [step,setStep]=useState(1);const [answers,setAnswers]=useState({job:params.get('job')||'',area:'',soil:'',implement:''})
 const set=(k,v)=>setAnswers(a=>({...a,[k]:v}))
 const results=useMemo(()=>tractors.map(t=>{let score=0;if(answers.job&&t.jobs.includes(answers.job))score+=4;if(answers.area==='small'&&t.power<=120)score+=3;if(answers.area==='medium'&&t.power>=120&&t.power<=170)score+=3;if(answers.area==='large'&&t.power>=160)score+=3;if(answers.soil==='heavy'&&t.power>=140)score+=2;if(answers.implement==='heavy'&&t.power>=160)score+=3;return {...t,score}}).sort((a,b)=>b.score-a.score||a.power-b.power).slice(0,3),[answers])
 return <><PageHero eyebrow="Интерактивный подбор" title="Подберите трактор за несколько шагов" lead="Ответьте на простые вопросы. Результат — предварительная рекомендация, а не замена консультации."/><section className="section"><div className="container selector-layout"><aside className="selector-progress">{[1,2,3,4].map(i=><button key={i} className={step===i?'active':step>i?'done':''} onClick={()=>setStep(i)}><span>{step>i?<CheckCircle2/>:i}</span><div><strong>{['Работа','Площадь','Почва','Оборудование'][i-1]}</strong><small>{['Что делаем','Какой объём','Насколько тяжёлая','Какое будет навесное'][i-1]}</small></div></button>)}</aside><div className="selector-panel">
  {step===1&&<div><h2>Какая основная работа?</h2><div className="choice-grid">{jobOptions.map(j=><button className={answers.job===j.id?'selected':''} onClick={()=>set('job',j.id)} key={j.id}><strong>{localize(j.label,lang)}</strong><span>{j.min}–{j.max} л.с.</span></button>)}</div></div>}
  {step===2&&<div><h2>Какой объём хозяйства?</h2><div className="choice-grid three">{[['small','До 100 га','Манёвренность и универсальность'],['medium','100–500 га','Баланс мощности и расхода'],['large','Более 500 га','Производительность и запас тяги']].map(x=><button className={answers.area===x[0]?'selected':''} onClick={()=>set('area',x[0])} key={x[0]}><strong>{x[1]}</strong><span>{x[2]}</span></button>)}</div></div>}
  {step===3&&<div><h2>Какая почва и рельеф?</h2><div className="choice-grid three">{[['light','Лёгкая / обработанная','Обычно требуется меньше тяги'],['mixed','Смешанные условия','Нужен универсальный запас'],['heavy','Плотная / тяжёлая','Нужна масса и больше мощности']].map(x=><button className={answers.soil===x[0]?'selected':''} onClick={()=>set('soil',x[0])} key={x[0]}><strong>{x[1]}</strong><span>{x[2]}</span></button>)}</div></div>}
  {step===4&&<div><h2>Самое тяжёлое оборудование</h2><div className="choice-grid three">{[['light','Лёгкое','Культиватор, опрыскиватель, прицеп'],['medium','Среднее','Плуг, сеялка, пресс-подборщик'],['heavy','Тяжёлое','Глубокорыхлитель, широкий посевной комплекс']].map(x=><button className={answers.implement===x[0]?'selected':''} onClick={()=>set('implement',x[0])} key={x[0]}><strong>{x[1]}</strong><span>{x[2]}</span></button>)}</div></div>}
  <div className="selector-nav"><button className="btn btn-ghost" disabled={step===1} onClick={()=>setStep(s=>s-1)}>Назад</button>{step<4?<button className="btn btn-dark" onClick={()=>setStep(s=>s+1)}>Дальше <ArrowRight/></button>:<a className="btn btn-gold" href="#results">Показать результат <ArrowRight/></a>}</div>
 </div></div></section><section id="results" className="section section-tinted"><div className="container"><div className="section-header"><span className="eyebrow">Результат</span><h2>Предварительно подходят</h2><p>Перед заказом менеджер проверит навесное оборудование, ширину захвата, тип почвы и комплектацию.</p></div><div className="cards-grid">{results.map(x=><TractorCard tractor={x} key={x.slug}/>)}</div><div className="selector-summary"><strong>Ваши ответы:</strong><span>{answers.job||'работа не выбрана'}</span><span>{answers.area||'площадь не выбрана'}</span><span>{answers.soil||'почва не выбрана'}</span><span>{answers.implement||'оборудование не выбрано'}</span><Link to="/contacts">Проверить подбор с менеджером <ArrowRight/></Link></div></div></section></>}
